### ISSUE TITLE
A3W_staticWeaponSaving = 0;  not working

### ISSUE THREAD

**Issue by codexGW** [micovery/ArmA3_Wasteland.Altis#13]
Static weapons purchased from the store are saved if A3W_staticWeaponSaving = 0;. R3F "Lock" and "Unlock" doesn't save no mater what A3W_staticWeaponSaving is set to, which could lead to confusion.

**Comment by IvanMMM** [comment]
Static weapons are saving at objects db in vanilla iniDB. You are saving them into vehicles. That could be the place where you can start searching :)

**Comment by micovery** [comment]
I moved it to be saved as a vehicle since it's makes more sense ... because you can actually get in them. 

Since they are being treated as vehicles, instead of objects ... the "locked/unlocked" state makes difference for saving purposes.

I think the fix is adding another condition in the `v_isVehicleSaveable` function.

https://github.com/micovery/ArmA3_Wasteland.Altis/blob/Development_main/persistence/world/vFunctions.sqf#L410

**Comment by micovery** [comment]
Fixed by 42219cc8307435da30f8f0337dff785dc6c4a774
