### ISSUE TITLE
Parking retrieve wait

### ISSUE THREAD

**Issue by codexGW** [micovery/ArmA3_Wasteland.Altis#49]
The parking retrieve wait seems to be bugged. You have to try retrieve a vehicle or just use the laptop before it starts counting down.

**Comment by micovery** [comment]
That's as-designed. Since there is no way to get an absolute time-stamp ... you can only count time elapsed relative to some point in time while the player is in the server.

If you start counting from the time the player parked the vehicle itself,  and the player leaves the server, and comes back after the server restarted ... then the original relative time-stamp is useless.

You cannot use two time-stamps from Arma across restarts to do math, and find the time-elapsed.

So in this case I just picked to count relative from the time he attempts to retrieve the vehicle itself. 
In this case, the best I can do is make it count relative to the point where the player joined the server itself. 

See:

http://feedback.arma3.com/view.php?id=22175

**Comment by codexGW** [comment]
I think it's best to make it start to count down when someone joins the server then have it reset when a retrieved vehicle spawns. Right now it resets the timer when you also fail to retrieve a vehicle. I like a count down when a player first joins because it prevents a player from going from Altis to Stratis and quickly spawning in vehicles so they don't unbalance the game to much.
