### ISSUE TITLE
Vehicle stats saving and loading

### ISSUE THREAD

**Issue by codexGW** [micovery/ArmA3_Wasteland.Altis#7]
Some of the vehicle stats are not saving and loading. 
TurretMagazines
AmmoCargo - What's the difference between TurretMagazines and AmmoCargo?
FuelCargo
RepairCargo

**Comment by micovery** [comment]
AmmoCargo - applicable for ammo trucks
FuelCargo - applicable for fuel trucks
RepairCargo - applicable for repair trucks

TurretMagazines - applicable to any vehicle that has gun turrets (can have more than one)

The Arma 3 commands for restoring the magazines, and ammo on vehicle gun turrets are kind of limited. You can restore the magazines, but you cannot force the exact number of ammunition in each magazine. There is however a command called setAmmo which sets the percentage of ammunition throughout all the magazines. 

I'll add some logic to do best-effort save/restore around turret magazines and ammo given the commands that are available.

**Comment by micovery** [comment]
Fixed part of the issues in b54f41c7cccbef0da9907798790805d184d60578

Vehicle hit points
Vehicle gas-tank fuel
Vehicle overall damage

should be now saved, and restored correctly.

As for the amount of magazines, and ammunition in each magazine ... that's a bit more complex, so for now I've disabled the restoring of the vehicle mags ... so that they don't start without any magazines.
